[component]
structures = [ "content_blocks" ]
label = "Content"
description = "Generic rich content area"
icon = "wysiwyg"
tags = ["Text"]

[props]
content_html = "<p>Praesent commodo cursus <strong>magna</strong>, vel scelerisque nisl consectetur et.</p>"
class = "Custom CSS classes"
